"""rename_card_id_to_pk

Revision ID: 5d5ea2c14455
Revises: 25c078a94915
Create Date: 2024-06-10 20:36:26.915541

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d5ea2c14455"
down_revision: Union[str, None] = "25c078a94915"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_cards_card_id", table_name="cards")
    op.alter_column("cards", "card_id", new_column_name="id")
    op.create_index(op.f("ix_cards_id"), "cards", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cards_id"), table_name="cards")
    op.alter_column("cards", "id", new_column_name="card_id")
    op.create_index("ix_cards_card_id", "cards", ["card_id"], unique=False)
    # ### end Alembic commands ###
