"""initial_migration

Revision ID: 77817c3ababe
Revises: 
Create Date: 2024-12-07 17:17:16.749318

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "77817c3ababe"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "card",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("word", sa.String(), nullable=False),
        sa.Column("meaning", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_card_id"), "card", ["id"], unique=False)
    op.create_table(
        "deck",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_deck_id"), "deck", ["id"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("login", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.create_table(
        "deck_card",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deck_id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"], ["card.id"], name="user_deck_card_id_fkey", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["deck_id"], ["deck.id"], name="user_deck_deck_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("deck_id", "card_id", name="unique_deck_card"),
    )
    op.create_index(op.f("ix_deck_card_id"), "deck_card", ["id"], unique=False)
    op.create_table(
        "user_card",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("demo_time", sa.String(), nullable=False),
        sa.Column("study_day", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"], ["card.id"], name="user_card_card_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="user_card_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "card_id", name="unique_user_card"),
    )
    op.create_index(op.f("ix_user_card_id"), "user_card", ["id"], unique=False)
    op.create_table(
        "user_deck",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("deck_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deck_id"], ["deck.id"], name="user_deck_deck_id_fkey", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="user_deck_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "deck_id", name="unique_user_deck"),
    )
    op.create_index(op.f("ix_user_deck_id"), "user_deck", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_deck_id"), table_name="user_deck")
    op.drop_table("user_deck")
    op.drop_index(op.f("ix_user_card_id"), table_name="user_card")
    op.drop_table("user_card")
    op.drop_index(op.f("ix_deck_card_id"), table_name="deck_card")
    op.drop_table("deck_card")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_deck_id"), table_name="deck")
    op.drop_table("deck")
    op.drop_index(op.f("ix_card_id"), table_name="card")
    op.drop_table("card")
    # ### end Alembic commands ###
