"""added_decks_table

Revision ID: de8fe69ca3de
Revises: 5d5ea2c14455
Create Date: 2024-07-14 15:48:39.359676

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de8fe69ca3de"
down_revision: Union[str, None] = "5d5ea2c14455"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "decks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_decks_id"), "decks", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_decks_id"), table_name="decks")
    op.drop_table("decks")
    # ### end Alembic commands ###
