"""Add_status_to_user_card

Revision ID: f3eb2f855fa5
Revises: 77817c3ababe
Create Date: 2024-12-11 21:08:20.408514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3eb2f855fa5'
down_revision: Union[str, None] = '77817c3ababe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_card', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_card', 'status')
    # ### end Alembic commands ###
